### ISSUE TITLE
Write "Threading and processes" topic

### ISSUE THREAD

**Issue by jimfulton** [zopefoundation/zodbdocs#16]

**Comment by jamadden** [comment]
How do you feel about mentioning (somewhere, maybe here) that gevent is known to work well with ZODB? Well, at least with ZODB+RelStorage; it used to work with ZEO but I'm not sure about ZEO5 yet.

**Comment by jimfulton** [comment]
+1  IIUC, using gevent is equivalent to using threads, but I'd love to have a section or subtopic delved into it further as desired.

**Comment by tseaver** [comment]
This issue was moved to zopefoundation/ZODB#108
