### ISSUE TITLE
Write "Schema migration" topic

### ISSUE THREAD

**Issue by jimfulton** [zopefoundation/zodbdocs#19]

**Comment by jamadden** [comment]
`zope.generations` or is there another/new best practice? It's worked very well for us. 

Also working well is using `zope.schema` and its `createFieldProperties` (well actually our own [`nti.schema.fieldproperty.createDirectFieldProperties`](http://ntischema.readthedocs.io/en/latest/index.html)) to provide default values for missing properties automatically. That may be advanced usage though.

It might also be worth a mention that once you have a class that is persistent, you can't change it to be non-persistent, or vice versa, without running into trouble. It can be done, but it takes some effort.

**Comment by jimfulton** [comment]
Thanks.  These are good things to note.

FWIW, I think zope.generations was a good start. I'd like to see something simpler, or at least a simple pattern that I could explain here.  This will be a tricky topic to write. :)

**Comment by jamadden** [comment]
`zope.generations` doesn't seem especially complicated to me, but I guess we've been using it for awhile across a lot of projects. I'll see if any of my colleagues that have more recently come to it remember some starting pain points. (cc @cutz)

**Comment by jamadden** [comment]
Another thing worth mentioning might be that `zope.deferredimport` works wonders when you refactor classes from place to place. 

I seem to recall that there's a declarative zc or z3c tool that you can use to fix up the names in the database, but we've never actually done that.

It's also important to clean out stale .pyc files, or you might never know that you moved a class you shouldn't have or failed to leave a forward in place. Then you'll be confused by differences in environments/across machines. (Granted, that's more of a good-deplayment technique point, but that did bite us at least once in the early days.)

**Comment by jimfulton** [comment]
Well, zope.generations depends on the component architecture, which is fine if you have other reasons to use it.

Also, the default schema manager requires a package with modules with special names that have functions with special names that all feels rather boilerplate to me. <shrug>

I think it might be best to document the schema manager pattern and provide a link to zope.generations.  I might provide a simpler implementation, but I'd be afraid to do that without one that was battle tested.

**Comment by jimfulton** [comment]
I ended up including scheme migration in the topic on writing persistent objects.

I provided references to deferredimport and zope.generations.

WRT changing whether an object is persistent I added a note and an issue
