### ISSUE TITLE
Move these issues to the ZODB repository (and close this repo, at least to new issues)?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zodbdocs#25]
There's a tool to move the issues at https://github.com/google/github-issue-mover

**Comment by tseaver** [comment]
That tool worked well, thanks!  I will try closing the issues for this repo now.

**Comment by tseaver** [comment]
Unchecking the "Issues" option makes all the original URLs 404s.  Not such a good idea, I think.

**Comment by jamadden** [comment]
Oh, ick. That seems like a bad design.

**Comment by tseaver** [comment]
I just checked in templates for issues and pull requests embedding links to the ZODB URLs.  Not perfect (the links don't appear unless you preview the template), but something.
